version: "3.6"

services:

  nginx:
    container_name: ${APP_COMPOSE_PROJECT_NAME}_nginx
    image: nginx
    working_dir: '/app'
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/app:ro
      - nginx_logs:/var/log/nginx:rw
    depends_on:
      - php
    ports:
      - ${NGINX_PORT}:80

  php:
    container_name: ${APP_COMPOSE_PROJECT_NAME}_php
    image: docker.local/${CI_PROJECT_PATH}/php${PHP_VER}-dev:${CI_COMMIT_REF_SLUG}
    user: 1000:${UID}
    volumes:
      - ~/.composer/cache/:/.composer_cache/:rw
      - ./:/app:rw
      # ms sql specific
      #- /etc/passwd:/etc/passwd:ro
      #- /etc/group:/etc/group:ro
    working_dir: /app
    depends_on:
      - mysql
      - rabbitmq
    env_file:
      - .env

  mysql:
    container_name: ${APP_COMPOSE_PROJECT_NAME}_mysql
    image: percona:5.6
    volumes:
      - ./.docker/mysql/config/my.cfg:/etc/my.cnf:ro
      - ./.docker/mysql/initdb:/docker-entrypoint-initdb.d/:ro
      - db_data:/var/lib/mysql/
      - db_logs:/var/log/mysql/
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    env_file:
      - .env

  rabbitmq:
    container_name: ${APP_COMPOSE_PROJECT_NAME}_rabbitmq
    image: rabbitmq:3-management
    hostname: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - 15672:15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 10s
      timeout: 10s
      retries: 5
    env_file:
      - .env

  phpmyadmin:
    container_name: ${APP_COMPOSE_PROJECT_NAME}_phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - 9110:80
    depends_on:
      - mysql
    env_file:
      - .env

volumes:
  db_data:
  db_logs:
  rabbitmq_data:
  nginx_logs:
